[package]
name = "rustvello-core"
description = "Core traits and types for the Rustvello distributed task library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rustvello-proto = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
hostname = { workspace = true }
lru = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
croner = { workspace = true }

[lints]
workspace = true
