[package]
name = "rustvello-postgres"
description = "PostgreSQL backend implementations for Rustvello"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
rustvello-core = { workspace = true }
rustvello-proto = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
deadpool-postgres = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
tokio-postgres-rustls = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
rustls-native-certs = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }

[features]
fault-injection = []
tls = ["dep:tokio-postgres-rustls", "dep:rustls", "dep:rustls-native-certs", "dep:rustls-pemfile"]

[dev-dependencies]
tempfile = { workspace = true }
rustvello-test-suite = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tokio = { workspace = true, features = ["test-util", "macros"] }

[lints]
workspace = true
