//! PyO3 wrappers for MongoDB 3.6+ backend components.

use pyo3::prelude::*;
use std::sync::Arc;

use rustvello_core::client_data_store::{ClientDataStore, ClientDataStoreManager};
use rustvello_core::trigger::{TriggerManager, TriggerStore};
use rustvello_mongo3::prelude::*;
use rustvello_proto::config::ClientDataStoreConfig;

// ─── Connection Pool ───────────────────────────────────────────

/// Shared MongoDB 3.6+ connection pool for reuse across components.
#[pyclass(name = "RustMongo3Pool")]
pub struct PyMongo3Pool {
    pub(crate) inner: Arc<MongoPool>,
}

#[pymethods]
impl PyMongo3Pool {
    /// Create a new MongoDB pool from a connection URI, database name, and app ID.
    ///
    /// The effective database name is `{db_name}_{app_id}`, providing
    /// per-application isolation when multiple apps share the same cluster.
    #[new]
    fn new(uri: &str, db_name: &str, app_id: &str) -> Self {
        Self {
            inner: Arc::new(MongoPool::new(uri, db_name, app_id)),
        }
    }
}

// ─── Broker ────────────────────────────────────────────────────

#[pyclass(name = "RustMongo3Broker")]
pub struct PyMongo3Broker {
    pub(crate) inner: Arc<Mongo3Broker>,
}

#[pymethods]
impl PyMongo3Broker {
    #[new]
    fn new(pool: &PyMongo3Pool) -> Self {
        Self {
            inner: Arc::new(Mongo3Broker::new(Arc::clone(&pool.inner))),
        }
    }
}

impl_py_broker!(PyMongo3Broker);

// ─── Orchestrator ──────────────────────────────────────────────

#[pyclass(name = "RustMongo3Orchestrator")]
pub struct PyMongo3Orchestrator {
    pub(crate) inner: Arc<Mongo3Orchestrator>,
}

#[pymethods]
impl PyMongo3Orchestrator {
    #[new]
    fn new(pool: &PyMongo3Pool) -> Self {
        Self {
            inner: Arc::new(Mongo3Orchestrator::new(Arc::clone(&pool.inner))),
        }
    }
}

// All trait-forwarding methods generated by macro.
impl_py_orchestrator!(PyMongo3Orchestrator);

// ─── State Backend ─────────────────────────────────────────────

#[pyclass(name = "RustMongo3StateBackend")]
pub struct PyMongo3StateBackend {
    pub(crate) inner: Arc<Mongo3StateBackend>,
}

#[pymethods]
impl PyMongo3StateBackend {
    #[new]
    fn new(pool: &PyMongo3Pool) -> Self {
        Self {
            inner: Arc::new(Mongo3StateBackend::new(Arc::clone(&pool.inner))),
        }
    }
}

impl_py_state_backend!(PyMongo3StateBackend);

// ─── Trigger Store ─────────────────────────────────────────────

#[pyclass(name = "RustMongo3TriggerStore")]
pub struct PyMongo3TriggerStore {
    pub(crate) store: Arc<Mongo3TriggerStore>,
    pub(crate) manager: TriggerManager,
}

#[pymethods]
impl PyMongo3TriggerStore {
    #[new]
    fn new(pool: &PyMongo3Pool) -> Self {
        let store = Arc::new(Mongo3TriggerStore::new(Arc::clone(&pool.inner)));
        let manager = TriggerManager::new(Arc::clone(&store) as Arc<dyn TriggerStore>);
        Self { store, manager }
    }
}

impl_py_trigger_store!(PyMongo3TriggerStore);

// ─── Client Data Store ─────────────────────────────────────────

#[pyclass(name = "RustMongo3ClientDataStore")]
pub struct PyMongo3ClientDataStore {
    pub(crate) inner: Arc<ClientDataStoreManager>,
}

#[pymethods]
impl PyMongo3ClientDataStore {
    #[new]
    #[pyo3(signature = (pool, min_size_to_cache=1024, max_size_to_cache=0, local_cache_size=128))]
    fn new(
        pool: &PyMongo3Pool,
        min_size_to_cache: usize,
        max_size_to_cache: usize,
        local_cache_size: usize,
    ) -> Self {
        let backend: Arc<dyn ClientDataStore> =
            Arc::new(Mongo3ClientDataStore::new(Arc::clone(&pool.inner)));
        let mut config = ClientDataStoreConfig::default();
        config.min_size_to_cache = min_size_to_cache;
        config.max_size_to_cache = max_size_to_cache;
        config.local_cache_size = local_cache_size;
        let manager = ClientDataStoreManager::new(backend, config);
        Self {
            inner: Arc::new(manager),
        }
    }
}

impl_py_client_data_store!(PyMongo3ClientDataStore);

#[cfg(test)]
mod tests {}
