//! PyO3 wrappers for PostgreSQL backend components.

use pyo3::prelude::*;
use std::sync::Arc;

use rustvello_core::client_data_store::{ClientDataStore, ClientDataStoreManager};
use rustvello_core::trigger::{TriggerManager, TriggerStore};
use rustvello_postgres::db::Database;
use rustvello_postgres::prelude::*;
use rustvello_proto::config::ClientDataStoreConfig;

use crate::error::to_py_err;

// ─── Database Connection ───────────────────────────────────────

/// Shared PostgreSQL connection pool for reuse across components.
#[pyclass(name = "RustPostgresDatabase")]
pub struct PyPostgresDatabase {
    pub(crate) inner: Arc<Database>,
}

#[pymethods]
impl PyPostgresDatabase {
    /// Connect to a PostgreSQL database using a connection string.
    ///
    /// The `app_id` creates a dedicated schema for per-application isolation.
    #[new]
    fn new(connection_string: &str, app_id: &str) -> PyResult<Self> {
        let db = crate::runtime::shared_runtime()?
            .block_on(Database::connect(connection_string, app_id))
            .map_err(to_py_err)?;
        Ok(Self {
            inner: Arc::new(db),
        })
    }
}

// ─── Broker ────────────────────────────────────────────────────

#[pyclass(name = "RustPostgresBroker")]
pub struct PyPostgresBroker {
    pub(crate) inner: Arc<PostgresBroker>,
}

#[pymethods]
impl PyPostgresBroker {
    #[new]
    fn new(db: &PyPostgresDatabase) -> Self {
        Self {
            inner: Arc::new(PostgresBroker::new(Arc::clone(&db.inner))),
        }
    }
}

impl_py_broker!(PyPostgresBroker);

// ─── Orchestrator ──────────────────────────────────────────────

#[pyclass(name = "RustPostgresOrchestrator")]
pub struct PyPostgresOrchestrator {
    pub(crate) inner: Arc<PostgresOrchestrator>,
}

#[pymethods]
impl PyPostgresOrchestrator {
    #[new]
    fn new(db: &PyPostgresDatabase) -> Self {
        Self {
            inner: Arc::new(PostgresOrchestrator::new(Arc::clone(&db.inner))),
        }
    }
}

// All trait-forwarding methods generated by macro.
impl_py_orchestrator!(PyPostgresOrchestrator);

// ─── State Backend ─────────────────────────────────────────────

#[pyclass(name = "RustPostgresStateBackend")]
pub struct PyPostgresStateBackend {
    pub(crate) inner: Arc<PostgresStateBackend>,
}

#[pymethods]
impl PyPostgresStateBackend {
    #[new]
    fn new(db: &PyPostgresDatabase) -> Self {
        Self {
            inner: Arc::new(PostgresStateBackend::new(Arc::clone(&db.inner))),
        }
    }
}

impl_py_state_backend!(PyPostgresStateBackend);

// ─── Trigger Store ─────────────────────────────────────────────

#[pyclass(name = "RustPostgresTriggerStore")]
pub struct PyPostgresTriggerStore {
    pub(crate) store: Arc<PostgresTriggerStore>,
    pub(crate) manager: TriggerManager,
}

#[pymethods]
impl PyPostgresTriggerStore {
    #[new]
    fn new(db: &PyPostgresDatabase) -> Self {
        let store = Arc::new(PostgresTriggerStore::new(Arc::clone(&db.inner)));
        let manager = TriggerManager::new(Arc::clone(&store) as Arc<dyn TriggerStore>);
        Self { store, manager }
    }
}

impl_py_trigger_store!(PyPostgresTriggerStore);

// ─── Client Data Store ─────────────────────────────────────────

#[pyclass(name = "RustPostgresClientDataStore")]
pub struct PyPostgresClientDataStore {
    pub(crate) inner: Arc<ClientDataStoreManager>,
}

#[pymethods]
impl PyPostgresClientDataStore {
    #[new]
    #[pyo3(signature = (db, min_size_to_cache=1024, max_size_to_cache=0, local_cache_size=128))]
    fn new(
        db: &PyPostgresDatabase,
        min_size_to_cache: usize,
        max_size_to_cache: usize,
        local_cache_size: usize,
    ) -> Self {
        let backend: Arc<dyn ClientDataStore> =
            Arc::new(PostgresClientDataStore::new(Arc::clone(&db.inner)));
        let mut config = ClientDataStoreConfig::default();
        config.min_size_to_cache = min_size_to_cache;
        config.max_size_to_cache = max_size_to_cache;
        config.local_cache_size = local_cache_size;
        let manager = ClientDataStoreManager::new(backend, config);
        Self {
            inner: Arc::new(manager),
        }
    }
}

impl_py_client_data_store!(PyPostgresClientDataStore);

#[cfg(test)]
mod tests {}
