//! PyO3 wrappers for Redis backend components.

use pyo3::prelude::*;
use std::sync::Arc;

use rustvello_core::client_data_store::{ClientDataStore, ClientDataStoreManager};
use rustvello_core::trigger::{TriggerManager, TriggerStore};
use rustvello_proto::config::ClientDataStoreConfig;
use rustvello_redis::prelude::*;

use crate::error::to_py_err;

// ─── Connection Pool ───────────────────────────────────────────

/// Shared Redis connection pool for reuse across components.
#[pyclass(name = "RustRedisPool")]
pub struct PyRedisPool {
    pub(crate) inner: Arc<RedisPool>,
}

#[pymethods]
impl PyRedisPool {
    /// Create a new Redis connection pool from a URI and app ID.
    ///
    /// The `app_id` namespaces every key as `rustvello:{app_id}:…`.
    #[new]
    fn new(uri: &str, app_id: &str) -> PyResult<Self> {
        let pool = RedisPool::new(uri, app_id).map_err(to_py_err)?;
        Ok(Self {
            inner: Arc::new(pool),
        })
    }
}

// ─── Broker ────────────────────────────────────────────────────

#[pyclass(name = "RustRedisBroker")]
pub struct PyRedisBroker {
    pub(crate) inner: Arc<RedisBroker>,
}

#[pymethods]
impl PyRedisBroker {
    #[new]
    fn new(pool: &PyRedisPool) -> Self {
        Self {
            inner: Arc::new(RedisBroker::new(Arc::clone(&pool.inner))),
        }
    }
}

impl_py_broker!(PyRedisBroker);

// ─── Orchestrator ──────────────────────────────────────────────

#[pyclass(name = "RustRedisOrchestrator")]
pub struct PyRedisOrchestrator {
    pub(crate) inner: Arc<RedisOrchestrator>,
}

#[pymethods]
impl PyRedisOrchestrator {
    #[new]
    fn new(pool: &PyRedisPool) -> Self {
        Self {
            inner: Arc::new(RedisOrchestrator::new(Arc::clone(&pool.inner))),
        }
    }
}

// All trait-forwarding methods generated by macro.
impl_py_orchestrator!(PyRedisOrchestrator);

// ─── State Backend ─────────────────────────────────────────────

#[pyclass(name = "RustRedisStateBackend")]
pub struct PyRedisStateBackend {
    pub(crate) inner: Arc<RedisStateBackend>,
}

#[pymethods]
impl PyRedisStateBackend {
    #[new]
    fn new(pool: &PyRedisPool) -> Self {
        Self {
            inner: Arc::new(RedisStateBackend::new(Arc::clone(&pool.inner))),
        }
    }
}

impl_py_state_backend!(PyRedisStateBackend);

// ─── Trigger Store ─────────────────────────────────────────────

#[pyclass(name = "RustRedisTriggerStore")]
pub struct PyRedisTriggerStore {
    pub(crate) store: Arc<RedisTriggerStore>,
    pub(crate) manager: TriggerManager,
}

#[pymethods]
impl PyRedisTriggerStore {
    #[new]
    fn new(pool: &PyRedisPool) -> Self {
        let store = Arc::new(RedisTriggerStore::new(Arc::clone(&pool.inner)));
        let manager = TriggerManager::new(Arc::clone(&store) as Arc<dyn TriggerStore>);
        Self { store, manager }
    }
}

impl_py_trigger_store!(PyRedisTriggerStore);

// ─── Client Data Store ─────────────────────────────────────────

#[pyclass(name = "RustRedisClientDataStore")]
pub struct PyRedisClientDataStore {
    pub(crate) inner: Arc<ClientDataStoreManager>,
}

#[pymethods]
impl PyRedisClientDataStore {
    #[new]
    #[pyo3(signature = (pool, min_size_to_cache=1024, max_size_to_cache=0, local_cache_size=128))]
    fn new(
        pool: &PyRedisPool,
        min_size_to_cache: usize,
        max_size_to_cache: usize,
        local_cache_size: usize,
    ) -> Self {
        let backend: Arc<dyn ClientDataStore> =
            Arc::new(RedisClientDataStore::new(Arc::clone(&pool.inner)));
        let mut config = ClientDataStoreConfig::default();
        config.min_size_to_cache = min_size_to_cache;
        config.max_size_to_cache = max_size_to_cache;
        config.local_cache_size = local_cache_size;
        let manager = ClientDataStoreManager::new(backend, config);
        Self {
            inner: Arc::new(manager),
        }
    }
}

impl_py_client_data_store!(PyRedisClientDataStore);

#[cfg(test)]
mod tests {}
