//! PyO3 wrappers for SQLite backend components.

use pyo3::prelude::*;
use std::sync::Arc;

use rustvello_core::client_data_store::{ClientDataStore, ClientDataStoreManager};
use rustvello_core::trigger::{TriggerManager, TriggerStore};
use rustvello_proto::config::ClientDataStoreConfig;
use rustvello_sqlite::db::Database;
use rustvello_sqlite::prelude::*;

use crate::error::to_py_err;

// ─── Database Connection ───────────────────────────────────────

/// Shared SQLite database connection for reuse across components.
#[pyclass(name = "RustSqliteDatabase")]
pub struct PySqliteDatabase {
    pub(crate) inner: Arc<Database>,
}

#[pymethods]
impl PySqliteDatabase {
    /// Open (or create) a SQLite database at the given file path.
    ///
    /// The `app_id` is embedded in the filename for per-application isolation.
    #[new]
    fn new(path: &str, app_id: &str) -> PyResult<Self> {
        let db = Database::open(path, app_id).map_err(to_py_err)?;
        Ok(Self {
            inner: Arc::new(db),
        })
    }

    /// Create an in-memory SQLite database (useful for testing).
    #[staticmethod]
    fn in_memory() -> PyResult<Self> {
        let db = Database::in_memory().map_err(to_py_err)?;
        Ok(Self {
            inner: Arc::new(db),
        })
    }
}

// ─── Broker ────────────────────────────────────────────────────

#[pyclass(name = "RustSqliteBroker")]
pub struct PySqliteBroker {
    pub(crate) inner: Arc<SqliteBroker>,
}

#[pymethods]
impl PySqliteBroker {
    #[new]
    fn new(db: &PySqliteDatabase) -> Self {
        Self {
            inner: Arc::new(SqliteBroker::new(Arc::clone(&db.inner))),
        }
    }
}

impl_py_broker!(PySqliteBroker);

// ─── Orchestrator ──────────────────────────────────────────────

#[pyclass(name = "RustSqliteOrchestrator")]
pub struct PySqliteOrchestrator {
    pub(crate) inner: Arc<SqliteOrchestrator>,
}

#[pymethods]
impl PySqliteOrchestrator {
    #[new]
    fn new(db: &PySqliteDatabase) -> Self {
        Self {
            inner: Arc::new(SqliteOrchestrator::new(Arc::clone(&db.inner))),
        }
    }
}

// All trait-forwarding methods generated by macro.
impl_py_orchestrator!(PySqliteOrchestrator);

// ─── State Backend ─────────────────────────────────────────────

#[pyclass(name = "RustSqliteStateBackend")]
pub struct PySqliteStateBackend {
    pub(crate) inner: Arc<SqliteStateBackend>,
}

#[pymethods]
impl PySqliteStateBackend {
    #[new]
    fn new(db: &PySqliteDatabase) -> Self {
        Self {
            inner: Arc::new(SqliteStateBackend::new(Arc::clone(&db.inner))),
        }
    }
}

// All trait-forwarding methods generated by macro.
impl_py_state_backend!(PySqliteStateBackend);

// ─── Trigger Store ─────────────────────────────────────────────

#[pyclass(name = "RustSqliteTriggerStore")]
pub struct PySqliteTriggerStore {
    pub(crate) store: Arc<SqliteTriggerStore>,
    pub(crate) manager: TriggerManager,
}

#[pymethods]
impl PySqliteTriggerStore {
    #[new]
    fn new(db: &PySqliteDatabase) -> Self {
        let store = Arc::new(SqliteTriggerStore::new(Arc::clone(&db.inner)));
        let manager = TriggerManager::new(Arc::clone(&store) as Arc<dyn TriggerStore>);
        Self { store, manager }
    }
}

impl_py_trigger_store!(PySqliteTriggerStore);

// ─── Client Data Store ─────────────────────────────────────────

#[pyclass(name = "RustSqliteClientDataStore")]
pub struct PySqliteClientDataStore {
    pub(crate) inner: Arc<ClientDataStoreManager>,
}

#[pymethods]
impl PySqliteClientDataStore {
    #[new]
    #[pyo3(signature = (db, min_size_to_cache=1024, max_size_to_cache=0, local_cache_size=128))]
    fn new(
        db: &PySqliteDatabase,
        min_size_to_cache: usize,
        max_size_to_cache: usize,
        local_cache_size: usize,
    ) -> Self {
        let backend: Arc<dyn ClientDataStore> =
            Arc::new(SqliteClientDataStore::new(Arc::clone(&db.inner)));
        let mut config = ClientDataStoreConfig::default();
        config.min_size_to_cache = min_size_to_cache;
        config.max_size_to_cache = max_size_to_cache;
        config.local_cache_size = local_cache_size;
        let manager = ClientDataStoreManager::new(backend, config);
        Self {
            inner: Arc::new(manager),
        }
    }
}

impl_py_client_data_store!(PySqliteClientDataStore);

#[cfg(test)]
mod tests {
    use super::*;
    use pyo3::Python;
    use std::collections::BTreeMap;

    fn make_db() -> PySqliteDatabase {
        PySqliteDatabase::in_memory().unwrap()
    }

    const UUID1: &str = "550e8400-e29b-41d4-a716-446655440001";

    #[test]
    fn sqlite_broker_roundtrip() {
        Python::with_gil(|py| {
            let db = make_db();
            let broker = PySqliteBroker::new(&db);
            assert_eq!(broker.count_invocations(py).unwrap(), 0);
            broker.route_invocation(py, UUID1).unwrap();
            assert_eq!(broker.count_invocations(py).unwrap(), 1);
            let retrieved = broker.retrieve_invocation(py).unwrap();
            assert_eq!(retrieved.as_deref(), Some(UUID1));
        });
    }

    #[test]
    fn sqlite_state_backend_result() {
        Python::with_gil(|py| {
            let db = make_db();
            let sb = PySqliteStateBackend::new(&db);
            sb.upsert_invocation(py, UUID1, "mod", "func", BTreeMap::new(), None, None)
                .unwrap();
            sb.store_result(py, UUID1, "hello").unwrap();
            assert_eq!(sb.get_result(py, UUID1).unwrap().as_deref(), Some("hello"));
        });
    }

    #[test]
    fn sqlite_client_data_store_inline() {
        Python::with_gil(|py| {
            let db = make_db();
            let store = PySqliteClientDataStore::new(&db, 1024, 0, 128);
            let stored = store.store_if_large(py, "small").unwrap();
            assert_eq!(stored, "small");
        });
    }
}
