use pyo3::prelude::*;
use std::sync::Arc;

use rustvello_mem::state_backend::MemStateBackend;

/// Rust in-memory state backend exposed to Python.
///
/// Wraps `MemStateBackend` for fast invocation and result storage.
#[pyclass(name = "RustMemStateBackend")]
pub struct PyMemStateBackend {
    pub(crate) inner: Arc<MemStateBackend>,
}

#[pymethods]
impl PyMemStateBackend {
    #[new]
    fn new() -> Self {
        Self {
            inner: Arc::new(MemStateBackend::new()),
        }
    }
}

// All trait-forwarding methods generated by macro.
impl_py_state_backend!(PyMemStateBackend);

#[cfg(test)]
mod tests {
    use super::*;
    use pyo3::Python;
    use std::collections::BTreeMap;

    const UUID1: &str = "550e8400-e29b-41d4-a716-446655440001";
    const UUID2: &str = "550e8400-e29b-41d4-a716-446655440002";

    fn sample_args() -> BTreeMap<String, String> {
        let mut m = BTreeMap::new();
        m.insert("x".into(), "42".into());
        m
    }

    #[test]
    fn upsert_and_get_result() {
        Python::with_gil(|py| {
            let sb = PyMemStateBackend::new();
            sb.upsert_invocation(py, UUID1, "mod", "func", sample_args(), None, None)
                .unwrap();

            // No result yet
            assert_eq!(sb.get_result(py, UUID1).unwrap(), None);

            // Store result
            sb.store_result(py, UUID1, "hello").unwrap();
            assert_eq!(sb.get_result(py, UUID1).unwrap().as_deref(), Some("hello"));
        });
    }

    #[test]
    fn store_and_get_error() {
        Python::with_gil(|py| {
            let sb = PyMemStateBackend::new();
            sb.upsert_invocation(py, UUID1, "mod", "func", sample_args(), None, None)
                .unwrap();

            // No error yet
            assert_eq!(sb.get_error(py, UUID1).unwrap(), None);

            // Store error
            sb.store_error(py, UUID1, "ValueError", "bad input", Some("traceback here"))
                .unwrap();
            let err = sb.get_error(py, UUID1).unwrap().unwrap();
            assert!(err.contains("ValueError"));
            assert!(err.contains("bad input"));
        });
    }

    #[test]
    fn store_error_without_traceback() {
        Python::with_gil(|py| {
            let sb = PyMemStateBackend::new();
            sb.upsert_invocation(py, UUID1, "mod", "func", sample_args(), None, None)
                .unwrap();
            sb.store_error(py, UUID1, "RuntimeError", "oops", None)
                .unwrap();
            let err = sb.get_error(py, UUID1).unwrap().unwrap();
            assert!(err.contains("RuntimeError"));
        });
    }

    #[test]
    fn purge_clears_data() {
        Python::with_gil(|py| {
            let sb = PyMemStateBackend::new();
            sb.upsert_invocation(py, UUID1, "mod", "func", sample_args(), None, None)
                .unwrap();
            sb.store_result(py, UUID1, "result").unwrap();
            sb.purge(py).unwrap();
            // After purge, result is gone
            assert_eq!(sb.get_result(py, UUID1).unwrap(), None);
        });
    }

    #[test]
    fn multiple_invocations() {
        Python::with_gil(|py| {
            let sb = PyMemStateBackend::new();
            sb.upsert_invocation(py, UUID1, "mod", "func", sample_args(), None, None)
                .unwrap();
            sb.upsert_invocation(py, UUID2, "mod", "func", sample_args(), None, None)
                .unwrap();
            sb.store_result(py, UUID1, "result1").unwrap();
            sb.store_result(py, UUID2, "result2").unwrap();
            assert_eq!(
                sb.get_result(py, UUID1).unwrap().as_deref(),
                Some("result1")
            );
            assert_eq!(
                sb.get_result(py, UUID2).unwrap().as_deref(),
                Some("result2")
            );
        });
    }
}
