
[package]
name = "py-rustvello"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "rustvello"
crate-type = ["cdylib"]

[dependencies]
rustvello-python = { path = "../crates/rustvello-python", features = ["pymethods"] }

pyo3 = { workspace = true, features = ["extension-module", "experimental-async"] }

[package.metadata.maturin]
module-name = "rustvello"
