"""Type stubs for the compiled rustvello Rust extension module (PyO3)."""

from __future__ import annotations

from typing import Any

# ============================================================================
# Functions
# ============================================================================

def get_version() -> str: ...
def get_current_invocation_id() -> str | None: ...
def get_current_num_retries() -> int | None: ...
def get_current_workflow_info() -> tuple[str, str, str | None] | None: ...
def compute_args_id(serialized_args: dict[str, str]) -> str: ...
def init_logging(
    level: str = "info",
    format: str = "text",
    use_colors: bool | None = None,
    compact_context: bool = True,
    stream: str = "stderr",
) -> None: ...
def status_to_serde(name: str) -> str: ...
def status_from_serde(serde_name: str) -> str: ...

# ============================================================================
# Identifiers
# ============================================================================

class TaskId:
    def __init__(self, module: str, name: str) -> None: ...
    @property
    def module(self) -> str: ...
    @property
    def name(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class InvocationId:
    def __init__(self) -> None: ...
    @staticmethod
    def from_string(id: str) -> InvocationId: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Status & Concurrency
# ============================================================================

class InvocationStatus:
    @staticmethod
    def registered() -> InvocationStatus: ...
    @staticmethod
    def pending() -> InvocationStatus: ...
    @staticmethod
    def running() -> InvocationStatus: ...
    @staticmethod
    def success() -> InvocationStatus: ...
    @staticmethod
    def failed() -> InvocationStatus: ...
    @staticmethod
    def retry() -> InvocationStatus: ...
    @staticmethod
    def concurrency_controlled() -> InvocationStatus: ...
    @staticmethod
    def concurrency_controlled_final() -> InvocationStatus: ...
    @staticmethod
    def rerouted() -> InvocationStatus: ...
    @staticmethod
    def pending_recovery() -> InvocationStatus: ...
    @staticmethod
    def running_recovery() -> InvocationStatus: ...
    def is_terminal(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ConcurrencyControlType:
    @staticmethod
    def unlimited() -> ConcurrencyControlType: ...
    @staticmethod
    def task() -> ConcurrencyControlType: ...
    @staticmethod
    def argument() -> ConcurrencyControlType: ...
    @staticmethod
    def none() -> ConcurrencyControlType: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Configuration
# ============================================================================

class TaskConfig:
    def __init__(
        self,
        max_retries: int = 0,
        concurrency_control: str = "unlimited",
        running_concurrency: int | None = None,
        cache_results: bool = False,
    ) -> None: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def cache_results(self) -> bool: ...
    @property
    def running_concurrency(self) -> int | None: ...
    def __repr__(self) -> str: ...

class AppConfig:
    def __init__(
        self,
        app_id: str = "rustvello",
        dev_mode_force_sync: bool = False,
        max_pending_seconds: int | None = None,
        heartbeat_interval_seconds: int | None = None,
        runner_dead_after_seconds: int | None = None,
        recovery_check_interval_seconds: int | None = None,
        scheduler_interval_seconds: int | None = None,
        enable_scheduler: bool | None = None,
        blocking_control: bool | None = None,
    ) -> None: ...
    @property
    def app_id(self) -> str: ...
    @property
    def dev_mode_force_sync(self) -> bool: ...
    @property
    def max_pending_seconds(self) -> int: ...
    @property
    def heartbeat_interval_seconds(self) -> int: ...
    @property
    def runner_dead_after_seconds(self) -> int: ...
    @property
    def recovery_check_interval_seconds(self) -> int: ...
    @property
    def scheduler_interval_seconds(self) -> int: ...
    @property
    def enable_scheduler(self) -> bool: ...
    @property
    def blocking_control(self) -> bool: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Invocation Result
# ============================================================================

class InvocationResult:
    @property
    def invocation_id(self) -> InvocationId: ...
    @property
    def status(self) -> InvocationStatus: ...
    @property
    def result(self) -> str | None: ...
    @property
    def error(self) -> str | None: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Main Application
# ============================================================================

class Rustvello:
    def __init__(self, config: AppConfig | None = None) -> None: ...
    def register_task(
        self,
        module: str,
        name: str,
        func: Any,
        config: TaskConfig | None = None,
    ) -> None: ...
    def submit(
        self,
        module: str,
        name: str,
        kwargs: dict[str, str] | None = None,
    ) -> InvocationId: ...
    def call_sync(
        self,
        module: str,
        name: str,
        kwargs: dict[str, str] | None = None,
    ) -> str | None: ...
    def get_status(self, invocation_id: InvocationId) -> InvocationStatus: ...
    def get_result(self, invocation_id: InvocationId) -> str | None: ...
    @staticmethod
    def from_backends(
        orchestrator: Any,
        state_backend: Any,
        broker: Any,
        trigger: Any,
        client_data_store: Any,
        config: AppConfig | None = None,
    ) -> Rustvello: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Runner
# ============================================================================

class RustTaskRunnerBuilder:
    def __init__(self, app_id: str = "rustvello") -> None: ...
    def memory(self) -> RustTaskRunnerBuilder: ...
    def with_backends(
        self,
        broker: Any,
        orchestrator: Any,
        state_backend: Any,
        trigger_store: Any | None = None,
    ) -> RustTaskRunnerBuilder: ...
    def with_num_workers(self, n: int) -> RustTaskRunnerBuilder: ...
    def with_idle_sleep(self, ms: int) -> RustTaskRunnerBuilder: ...
    def with_config(self, config: AppConfig) -> RustTaskRunnerBuilder: ...
    def register_task(
        self,
        module: str,
        name: str,
        func: Any,
        *,
        concurrency_control: str = "Unlimited",
        running_concurrency: int | None = None,
        key_arguments: list[str] = ...,
        reroute_on_cc: bool = False,
        max_retries: int = 0,
        retry_for_errors: list[str] = ...,
        registration_concurrency: str = "Unlimited",
        cache_results: bool = False,
        disable_cache_args: list[str] = ...,
        on_diff_non_key_args_raise: bool = False,
        parallel_batch_size: int = 100,
        is_workflow_task: bool = False,
    ) -> None: ...
    def build(self) -> RustTaskRunner: ...

class RustTaskRunner:
    def runner_id(self) -> str: ...
    def active_invocations(self) -> list[tuple[str, str]]: ...
    def run_one(self) -> bool: ...
    def run(self) -> None: ...
    def shutdown(self) -> None: ...

# ============================================================================
# Connection / Pool Classes
# ============================================================================

class RustSqliteDatabase:
    def __init__(self, path: str, app_id: str) -> None: ...
    @staticmethod
    def in_memory() -> RustSqliteDatabase: ...

class RustPostgresDatabase:
    def __init__(self, connection_string: str, app_id: str) -> None: ...

class RustRedisPool:
    def __init__(self, uri: str, app_id: str) -> None: ...

class RustMongoPool:
    def __init__(self, uri: str, db_name: str, app_id: str) -> None: ...

class RustMongo3Pool:
    def __init__(self, uri: str, db_name: str, app_id: str) -> None: ...

# ============================================================================
# Orchestrator — all backends share the same methods
# ============================================================================

class RustMemOrchestrator:
    def __init__(self) -> None: ...
    def get_invocation_status(self, invocation_id: str) -> tuple[str, str | None, float]: ...
    def set_invocation_status(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def set_waiting_for(self, waiter: str, waited_on: str) -> None: ...
    def release_waiters(self, completed: str) -> list[str]: ...
    def get_waiters(self, waited_on: str) -> list[str]: ...
    def register_invocation(
        self,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
    ) -> str: ...
    def register_invocation_with_id(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def increment_invocation_retries(self, invocation_id: str) -> int: ...
    def get_invocation_retries(self, invocation_id: str) -> int: ...
    def remove_invocation(self, invocation_id: str) -> None: ...
    def purge(self) -> None: ...
    def check_running_concurrency(
        self,
        task_module: str,
        task_name: str,
        task_config_json: str,
        cc_args: dict[str, str] | None = None,
    ) -> bool: ...
    def index_for_concurrency_control(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        cc_args: dict[str, str] | None = None,
    ) -> None: ...
    def remove_from_concurrency_index(self, invocation_id: str) -> None: ...
    def schedule_auto_purge(self, invocation_id: str) -> None: ...
    def run_auto_purge(self, max_age_secs: int) -> list[str]: ...
    def get_invocations_by_status(
        self,
        status: str,
        task_module: str | None = None,
        task_name: str | None = None,
    ) -> list[str]: ...
    def get_invocations_by_task(self, task_module: str, task_name: str) -> list[str]: ...
    def get_invocations_by_call(self, call_id: str) -> list[str]: ...
    def count_invocations(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
    ) -> int: ...
    def get_invocation_ids_paginated(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[str]: ...
    def filter_by_status(self, invocation_ids: list[str], statuses: list[str]) -> list[str]: ...
    def get_blocking_invocations(self, max_num: int = 100) -> list[str]: ...
    def get_existing_invocations(
        self,
        task_module: str,
        task_name: str,
        statuses: list[str],
        cc_args: dict[str, str] | None = None,
    ) -> list[str]: ...
    def register_heartbeat(self, runner_id: str, can_run_atomic_service: bool = False) -> None: ...
    def get_stale_pending_invocations(self, max_pending_seconds: int) -> list[str]: ...
    def get_stale_running_invocations(self, runner_dead_after_seconds: int) -> list[str]: ...
    def get_active_runner_ids(self, timeout_seconds: int) -> list[str]: ...
    def get_active_runners(
        self,
        timeout_seconds: int,
        can_run_atomic_service: bool | None = None,
    ) -> list[dict[str, Any]]: ...
    def record_atomic_service_execution(self, runner_id: str, start_ts: float, end_ts: float) -> None: ...
    def get_atomic_service_timeline(self) -> list[dict[str, Any]]: ...

class RustSqliteOrchestrator:
    def __init__(self, db: RustSqliteDatabase) -> None: ...
    def get_invocation_status(self, invocation_id: str) -> tuple[str, str | None, float]: ...
    def set_invocation_status(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def set_waiting_for(self, waiter: str, waited_on: str) -> None: ...
    def release_waiters(self, completed: str) -> list[str]: ...
    def get_waiters(self, waited_on: str) -> list[str]: ...
    def register_invocation(
        self,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
    ) -> str: ...
    def register_invocation_with_id(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def increment_invocation_retries(self, invocation_id: str) -> int: ...
    def get_invocation_retries(self, invocation_id: str) -> int: ...
    def remove_invocation(self, invocation_id: str) -> None: ...
    def purge(self) -> None: ...
    def check_running_concurrency(
        self,
        task_module: str,
        task_name: str,
        task_config_json: str,
        cc_args: dict[str, str] | None = None,
    ) -> bool: ...
    def index_for_concurrency_control(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        cc_args: dict[str, str] | None = None,
    ) -> None: ...
    def remove_from_concurrency_index(self, invocation_id: str) -> None: ...
    def schedule_auto_purge(self, invocation_id: str) -> None: ...
    def run_auto_purge(self, max_age_secs: int) -> list[str]: ...
    def get_invocations_by_status(
        self,
        status: str,
        task_module: str | None = None,
        task_name: str | None = None,
    ) -> list[str]: ...
    def get_invocations_by_task(self, task_module: str, task_name: str) -> list[str]: ...
    def get_invocations_by_call(self, call_id: str) -> list[str]: ...
    def count_invocations(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
    ) -> int: ...
    def get_invocation_ids_paginated(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[str]: ...
    def filter_by_status(self, invocation_ids: list[str], statuses: list[str]) -> list[str]: ...
    def get_blocking_invocations(self, max_num: int = 100) -> list[str]: ...
    def get_existing_invocations(
        self,
        task_module: str,
        task_name: str,
        statuses: list[str],
        cc_args: dict[str, str] | None = None,
    ) -> list[str]: ...
    def register_heartbeat(self, runner_id: str, can_run_atomic_service: bool = False) -> None: ...
    def get_stale_pending_invocations(self, max_pending_seconds: int) -> list[str]: ...
    def get_stale_running_invocations(self, runner_dead_after_seconds: int) -> list[str]: ...
    def get_active_runner_ids(self, timeout_seconds: int) -> list[str]: ...
    def get_active_runners(
        self,
        timeout_seconds: int,
        can_run_atomic_service: bool | None = None,
    ) -> list[dict[str, Any]]: ...
    def record_atomic_service_execution(self, runner_id: str, start_ts: float, end_ts: float) -> None: ...
    def get_atomic_service_timeline(self) -> list[dict[str, Any]]: ...

class RustPostgresOrchestrator:
    def __init__(self, db: RustPostgresDatabase) -> None: ...
    def get_invocation_status(self, invocation_id: str) -> tuple[str, str | None, float]: ...
    def set_invocation_status(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def set_waiting_for(self, waiter: str, waited_on: str) -> None: ...
    def release_waiters(self, completed: str) -> list[str]: ...
    def get_waiters(self, waited_on: str) -> list[str]: ...
    def register_invocation(
        self,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
    ) -> str: ...
    def register_invocation_with_id(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def increment_invocation_retries(self, invocation_id: str) -> int: ...
    def get_invocation_retries(self, invocation_id: str) -> int: ...
    def remove_invocation(self, invocation_id: str) -> None: ...
    def purge(self) -> None: ...
    def check_running_concurrency(
        self,
        task_module: str,
        task_name: str,
        task_config_json: str,
        cc_args: dict[str, str] | None = None,
    ) -> bool: ...
    def index_for_concurrency_control(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        cc_args: dict[str, str] | None = None,
    ) -> None: ...
    def remove_from_concurrency_index(self, invocation_id: str) -> None: ...
    def schedule_auto_purge(self, invocation_id: str) -> None: ...
    def run_auto_purge(self, max_age_secs: int) -> list[str]: ...
    def get_invocations_by_status(
        self,
        status: str,
        task_module: str | None = None,
        task_name: str | None = None,
    ) -> list[str]: ...
    def get_invocations_by_task(self, task_module: str, task_name: str) -> list[str]: ...
    def get_invocations_by_call(self, call_id: str) -> list[str]: ...
    def count_invocations(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
    ) -> int: ...
    def get_invocation_ids_paginated(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[str]: ...
    def filter_by_status(self, invocation_ids: list[str], statuses: list[str]) -> list[str]: ...
    def get_blocking_invocations(self, max_num: int = 100) -> list[str]: ...
    def get_existing_invocations(
        self,
        task_module: str,
        task_name: str,
        statuses: list[str],
        cc_args: dict[str, str] | None = None,
    ) -> list[str]: ...
    def register_heartbeat(self, runner_id: str, can_run_atomic_service: bool = False) -> None: ...
    def get_stale_pending_invocations(self, max_pending_seconds: int) -> list[str]: ...
    def get_stale_running_invocations(self, runner_dead_after_seconds: int) -> list[str]: ...
    def get_active_runner_ids(self, timeout_seconds: int) -> list[str]: ...
    def get_active_runners(
        self,
        timeout_seconds: int,
        can_run_atomic_service: bool | None = None,
    ) -> list[dict[str, Any]]: ...
    def record_atomic_service_execution(self, runner_id: str, start_ts: float, end_ts: float) -> None: ...
    def get_atomic_service_timeline(self) -> list[dict[str, Any]]: ...

class RustRedisOrchestrator:
    def __init__(self, pool: RustRedisPool) -> None: ...
    def get_invocation_status(self, invocation_id: str) -> tuple[str, str | None, float]: ...
    def set_invocation_status(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def set_waiting_for(self, waiter: str, waited_on: str) -> None: ...
    def release_waiters(self, completed: str) -> list[str]: ...
    def get_waiters(self, waited_on: str) -> list[str]: ...
    def register_invocation(
        self,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
    ) -> str: ...
    def register_invocation_with_id(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def increment_invocation_retries(self, invocation_id: str) -> int: ...
    def get_invocation_retries(self, invocation_id: str) -> int: ...
    def remove_invocation(self, invocation_id: str) -> None: ...
    def purge(self) -> None: ...
    def check_running_concurrency(
        self,
        task_module: str,
        task_name: str,
        task_config_json: str,
        cc_args: dict[str, str] | None = None,
    ) -> bool: ...
    def index_for_concurrency_control(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        cc_args: dict[str, str] | None = None,
    ) -> None: ...
    def remove_from_concurrency_index(self, invocation_id: str) -> None: ...
    def schedule_auto_purge(self, invocation_id: str) -> None: ...
    def run_auto_purge(self, max_age_secs: int) -> list[str]: ...
    def get_invocations_by_status(
        self,
        status: str,
        task_module: str | None = None,
        task_name: str | None = None,
    ) -> list[str]: ...
    def get_invocations_by_task(self, task_module: str, task_name: str) -> list[str]: ...
    def get_invocations_by_call(self, call_id: str) -> list[str]: ...
    def count_invocations(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
    ) -> int: ...
    def get_invocation_ids_paginated(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[str]: ...
    def filter_by_status(self, invocation_ids: list[str], statuses: list[str]) -> list[str]: ...
    def get_blocking_invocations(self, max_num: int = 100) -> list[str]: ...
    def get_existing_invocations(
        self,
        task_module: str,
        task_name: str,
        statuses: list[str],
        cc_args: dict[str, str] | None = None,
    ) -> list[str]: ...
    def register_heartbeat(self, runner_id: str, can_run_atomic_service: bool = False) -> None: ...
    def get_stale_pending_invocations(self, max_pending_seconds: int) -> list[str]: ...
    def get_stale_running_invocations(self, runner_dead_after_seconds: int) -> list[str]: ...
    def get_active_runner_ids(self, timeout_seconds: int) -> list[str]: ...
    def get_active_runners(
        self,
        timeout_seconds: int,
        can_run_atomic_service: bool | None = None,
    ) -> list[dict[str, Any]]: ...
    def record_atomic_service_execution(self, runner_id: str, start_ts: float, end_ts: float) -> None: ...
    def get_atomic_service_timeline(self) -> list[dict[str, Any]]: ...

class RustMongoOrchestrator:
    def __init__(self, pool: RustMongoPool) -> None: ...
    def get_invocation_status(self, invocation_id: str) -> tuple[str, str | None, float]: ...
    def set_invocation_status(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def set_waiting_for(self, waiter: str, waited_on: str) -> None: ...
    def release_waiters(self, completed: str) -> list[str]: ...
    def get_waiters(self, waited_on: str) -> list[str]: ...
    def register_invocation(
        self,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
    ) -> str: ...
    def register_invocation_with_id(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def increment_invocation_retries(self, invocation_id: str) -> int: ...
    def get_invocation_retries(self, invocation_id: str) -> int: ...
    def remove_invocation(self, invocation_id: str) -> None: ...
    def purge(self) -> None: ...
    def check_running_concurrency(
        self,
        task_module: str,
        task_name: str,
        task_config_json: str,
        cc_args: dict[str, str] | None = None,
    ) -> bool: ...
    def index_for_concurrency_control(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        cc_args: dict[str, str] | None = None,
    ) -> None: ...
    def remove_from_concurrency_index(self, invocation_id: str) -> None: ...
    def schedule_auto_purge(self, invocation_id: str) -> None: ...
    def run_auto_purge(self, max_age_secs: int) -> list[str]: ...
    def get_invocations_by_status(
        self,
        status: str,
        task_module: str | None = None,
        task_name: str | None = None,
    ) -> list[str]: ...
    def get_invocations_by_task(self, task_module: str, task_name: str) -> list[str]: ...
    def get_invocations_by_call(self, call_id: str) -> list[str]: ...
    def count_invocations(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
    ) -> int: ...
    def get_invocation_ids_paginated(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[str]: ...
    def filter_by_status(self, invocation_ids: list[str], statuses: list[str]) -> list[str]: ...
    def get_blocking_invocations(self, max_num: int = 100) -> list[str]: ...
    def get_existing_invocations(
        self,
        task_module: str,
        task_name: str,
        statuses: list[str],
        cc_args: dict[str, str] | None = None,
    ) -> list[str]: ...
    def register_heartbeat(self, runner_id: str, can_run_atomic_service: bool = False) -> None: ...
    def get_stale_pending_invocations(self, max_pending_seconds: int) -> list[str]: ...
    def get_stale_running_invocations(self, runner_dead_after_seconds: int) -> list[str]: ...
    def get_active_runner_ids(self, timeout_seconds: int) -> list[str]: ...
    def get_active_runners(
        self,
        timeout_seconds: int,
        can_run_atomic_service: bool | None = None,
    ) -> list[dict[str, Any]]: ...
    def record_atomic_service_execution(self, runner_id: str, start_ts: float, end_ts: float) -> None: ...
    def get_atomic_service_timeline(self) -> list[dict[str, Any]]: ...

class RustMongo3Orchestrator:
    def __init__(self, pool: RustMongo3Pool) -> None: ...
    def get_invocation_status(self, invocation_id: str) -> tuple[str, str | None, float]: ...
    def set_invocation_status(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def set_waiting_for(self, waiter: str, waited_on: str) -> None: ...
    def release_waiters(self, completed: str) -> list[str]: ...
    def get_waiters(self, waited_on: str) -> list[str]: ...
    def register_invocation(
        self,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
    ) -> str: ...
    def register_invocation_with_id(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        runner_id: str | None = None,
    ) -> tuple[str, str | None, float]: ...
    def increment_invocation_retries(self, invocation_id: str) -> int: ...
    def get_invocation_retries(self, invocation_id: str) -> int: ...
    def remove_invocation(self, invocation_id: str) -> None: ...
    def purge(self) -> None: ...
    def check_running_concurrency(
        self,
        task_module: str,
        task_name: str,
        task_config_json: str,
        cc_args: dict[str, str] | None = None,
    ) -> bool: ...
    def index_for_concurrency_control(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        cc_args: dict[str, str] | None = None,
    ) -> None: ...
    def remove_from_concurrency_index(self, invocation_id: str) -> None: ...
    def schedule_auto_purge(self, invocation_id: str) -> None: ...
    def run_auto_purge(self, max_age_secs: int) -> list[str]: ...
    def get_invocations_by_status(
        self,
        status: str,
        task_module: str | None = None,
        task_name: str | None = None,
    ) -> list[str]: ...
    def get_invocations_by_task(self, task_module: str, task_name: str) -> list[str]: ...
    def get_invocations_by_call(self, call_id: str) -> list[str]: ...
    def count_invocations(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
    ) -> int: ...
    def get_invocation_ids_paginated(
        self,
        task_module: str | None = None,
        task_name: str | None = None,
        statuses: list[str] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[str]: ...
    def filter_by_status(self, invocation_ids: list[str], statuses: list[str]) -> list[str]: ...
    def get_blocking_invocations(self, max_num: int = 100) -> list[str]: ...
    def get_existing_invocations(
        self,
        task_module: str,
        task_name: str,
        statuses: list[str],
        cc_args: dict[str, str] | None = None,
    ) -> list[str]: ...
    def register_heartbeat(self, runner_id: str, can_run_atomic_service: bool = False) -> None: ...
    def get_stale_pending_invocations(self, max_pending_seconds: int) -> list[str]: ...
    def get_stale_running_invocations(self, runner_dead_after_seconds: int) -> list[str]: ...
    def get_active_runner_ids(self, timeout_seconds: int) -> list[str]: ...
    def get_active_runners(
        self,
        timeout_seconds: int,
        can_run_atomic_service: bool | None = None,
    ) -> list[dict[str, Any]]: ...
    def record_atomic_service_execution(self, runner_id: str, start_ts: float, end_ts: float) -> None: ...
    def get_atomic_service_timeline(self) -> list[dict[str, Any]]: ...

# ============================================================================
# State Backend — all backends share the same methods
# ============================================================================

class RustMemStateBackend:
    def __init__(self) -> None: ...
    def upsert_invocation(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        parent_invocation_id: str | None = None,
        workflow_json: str | None = None,
    ) -> None: ...
    def store_result(self, invocation_id: str, result: str) -> None: ...
    def get_result(self, invocation_id: str) -> str | None: ...
    def store_error(
        self,
        invocation_id: str,
        error_type: str,
        message: str,
        traceback: str | None = None,
    ) -> None: ...
    def get_error(self, invocation_id: str) -> str | None: ...
    def get_error_json(self, invocation_id: str) -> str | None: ...
    def purge(self) -> None: ...
    def add_history(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
        runner_context_id: str | None = None,
        message: str | None = None,
        sr_timestamp_us: int | None = None,
        history_timestamp_us: int | None = None,
    ) -> None: ...
    def get_history(self, invocation_id: str) -> str: ...
    def get_invocation(self, invocation_id: str) -> str: ...
    def get_call(self, call_id: str) -> str: ...
    def get_child_invocations(self, parent_invocation_id: str) -> list[str]: ...
    def store_workflow_run(self, workflow_json: str) -> None: ...
    def get_all_workflow_types(self) -> list[str]: ...
    def get_workflow_runs(self, task_module: str, task_name: str) -> list[str]: ...
    def set_workflow_data(self, workflow_invocation_id: str, key: str, value: str) -> None: ...
    def get_workflow_data(self, workflow_invocation_id: str, key: str) -> str | None: ...
    def get_workflow_invocations(self, workflow_id: str) -> list[str]: ...
    def store_app_info(self, app_id: str, info_json: str) -> None: ...
    def get_app_info(self, app_id: str) -> str | None: ...
    def get_all_app_infos(self) -> list[tuple[str, str]]: ...
    def store_workflow_sub_invocation(self, workflow_id: str, sub_invocation_id: str) -> None: ...
    def get_workflow_sub_invocations(self, workflow_id: str) -> list[str]: ...
    def get_all_workflow_runs(self) -> list[str]: ...
    def store_runner_context(
        self,
        runner_id: str,
        runner_cls: str,
        pid: int,
        hostname: str,
        thread_id: int,
        parent_runner_id: str | None = None,
        parent_runner_cls: str | None = None,
    ) -> None: ...
    def get_runner_context(self, runner_id: str) -> str | None: ...
    def get_all_runner_contexts(self) -> list[tuple[str, str]]: ...
    def remove_runner_context(self, runner_id: str) -> None: ...
    def heartbeat_runner(self, runner_id: str) -> None: ...
    def get_stale_runners(self, timeout_seconds: int) -> list[tuple[str, str]]: ...

class RustSqliteStateBackend:
    def __init__(self, db: RustSqliteDatabase) -> None: ...
    def upsert_invocation(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        parent_invocation_id: str | None = None,
        workflow_json: str | None = None,
    ) -> None: ...
    def store_result(self, invocation_id: str, result: str) -> None: ...
    def get_result(self, invocation_id: str) -> str | None: ...
    def store_error(self, invocation_id: str, error_type: str, message: str, traceback: str | None = None) -> None: ...
    def get_error(self, invocation_id: str) -> str | None: ...
    def get_error_json(self, invocation_id: str) -> str | None: ...
    def purge(self) -> None: ...
    def add_history(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
        runner_context_id: str | None = None,
        message: str | None = None,
        sr_timestamp_us: int | None = None,
        history_timestamp_us: int | None = None,
    ) -> None: ...
    def get_history(self, invocation_id: str) -> str: ...
    def get_invocation(self, invocation_id: str) -> str: ...
    def get_call(self, call_id: str) -> str: ...
    def get_child_invocations(self, parent_invocation_id: str) -> list[str]: ...
    def store_workflow_run(self, workflow_json: str) -> None: ...
    def get_all_workflow_types(self) -> list[str]: ...
    def get_workflow_runs(self, task_module: str, task_name: str) -> list[str]: ...
    def set_workflow_data(self, workflow_invocation_id: str, key: str, value: str) -> None: ...
    def get_workflow_data(self, workflow_invocation_id: str, key: str) -> str | None: ...
    def get_workflow_invocations(self, workflow_id: str) -> list[str]: ...
    def store_app_info(self, app_id: str, info_json: str) -> None: ...
    def get_app_info(self, app_id: str) -> str | None: ...
    def get_all_app_infos(self) -> list[tuple[str, str]]: ...
    def store_workflow_sub_invocation(self, workflow_id: str, sub_invocation_id: str) -> None: ...
    def get_workflow_sub_invocations(self, workflow_id: str) -> list[str]: ...
    def get_all_workflow_runs(self) -> list[str]: ...
    def store_runner_context(
        self,
        runner_id: str,
        runner_cls: str,
        pid: int,
        hostname: str,
        thread_id: int,
        parent_runner_id: str | None = None,
        parent_runner_cls: str | None = None,
    ) -> None: ...
    def get_runner_context(self, runner_id: str) -> str | None: ...
    def get_all_runner_contexts(self) -> list[tuple[str, str]]: ...
    def remove_runner_context(self, runner_id: str) -> None: ...
    def heartbeat_runner(self, runner_id: str) -> None: ...
    def get_stale_runners(self, timeout_seconds: int) -> list[tuple[str, str]]: ...

class RustPostgresStateBackend:
    def __init__(self, db: RustPostgresDatabase) -> None: ...
    def upsert_invocation(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        parent_invocation_id: str | None = None,
        workflow_json: str | None = None,
    ) -> None: ...
    def store_result(self, invocation_id: str, result: str) -> None: ...
    def get_result(self, invocation_id: str) -> str | None: ...
    def store_error(self, invocation_id: str, error_type: str, message: str, traceback: str | None = None) -> None: ...
    def get_error(self, invocation_id: str) -> str | None: ...
    def get_error_json(self, invocation_id: str) -> str | None: ...
    def purge(self) -> None: ...
    def add_history(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
        runner_context_id: str | None = None,
        message: str | None = None,
        sr_timestamp_us: int | None = None,
        history_timestamp_us: int | None = None,
    ) -> None: ...
    def get_history(self, invocation_id: str) -> str: ...
    def get_invocation(self, invocation_id: str) -> str: ...
    def get_call(self, call_id: str) -> str: ...
    def get_child_invocations(self, parent_invocation_id: str) -> list[str]: ...
    def store_workflow_run(self, workflow_json: str) -> None: ...
    def get_all_workflow_types(self) -> list[str]: ...
    def get_workflow_runs(self, task_module: str, task_name: str) -> list[str]: ...
    def set_workflow_data(self, workflow_invocation_id: str, key: str, value: str) -> None: ...
    def get_workflow_data(self, workflow_invocation_id: str, key: str) -> str | None: ...
    def get_workflow_invocations(self, workflow_id: str) -> list[str]: ...
    def store_app_info(self, app_id: str, info_json: str) -> None: ...
    def get_app_info(self, app_id: str) -> str | None: ...
    def get_all_app_infos(self) -> list[tuple[str, str]]: ...
    def store_workflow_sub_invocation(self, workflow_id: str, sub_invocation_id: str) -> None: ...
    def get_workflow_sub_invocations(self, workflow_id: str) -> list[str]: ...
    def get_all_workflow_runs(self) -> list[str]: ...
    def store_runner_context(
        self,
        runner_id: str,
        runner_cls: str,
        pid: int,
        hostname: str,
        thread_id: int,
        parent_runner_id: str | None = None,
        parent_runner_cls: str | None = None,
    ) -> None: ...
    def get_runner_context(self, runner_id: str) -> str | None: ...
    def get_all_runner_contexts(self) -> list[tuple[str, str]]: ...
    def remove_runner_context(self, runner_id: str) -> None: ...
    def heartbeat_runner(self, runner_id: str) -> None: ...
    def get_stale_runners(self, timeout_seconds: int) -> list[tuple[str, str]]: ...

class RustRedisStateBackend:
    def __init__(self, pool: RustRedisPool) -> None: ...
    def upsert_invocation(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        parent_invocation_id: str | None = None,
        workflow_json: str | None = None,
    ) -> None: ...
    def store_result(self, invocation_id: str, result: str) -> None: ...
    def get_result(self, invocation_id: str) -> str | None: ...
    def store_error(self, invocation_id: str, error_type: str, message: str, traceback: str | None = None) -> None: ...
    def get_error(self, invocation_id: str) -> str | None: ...
    def get_error_json(self, invocation_id: str) -> str | None: ...
    def purge(self) -> None: ...
    def add_history(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
        runner_context_id: str | None = None,
        message: str | None = None,
        sr_timestamp_us: int | None = None,
        history_timestamp_us: int | None = None,
    ) -> None: ...
    def get_history(self, invocation_id: str) -> str: ...
    def get_invocation(self, invocation_id: str) -> str: ...
    def get_call(self, call_id: str) -> str: ...
    def get_child_invocations(self, parent_invocation_id: str) -> list[str]: ...
    def store_workflow_run(self, workflow_json: str) -> None: ...
    def get_all_workflow_types(self) -> list[str]: ...
    def get_workflow_runs(self, task_module: str, task_name: str) -> list[str]: ...
    def set_workflow_data(self, workflow_invocation_id: str, key: str, value: str) -> None: ...
    def get_workflow_data(self, workflow_invocation_id: str, key: str) -> str | None: ...
    def get_workflow_invocations(self, workflow_id: str) -> list[str]: ...
    def store_app_info(self, app_id: str, info_json: str) -> None: ...
    def get_app_info(self, app_id: str) -> str | None: ...
    def get_all_app_infos(self) -> list[tuple[str, str]]: ...
    def store_workflow_sub_invocation(self, workflow_id: str, sub_invocation_id: str) -> None: ...
    def get_workflow_sub_invocations(self, workflow_id: str) -> list[str]: ...
    def get_all_workflow_runs(self) -> list[str]: ...
    def store_runner_context(
        self,
        runner_id: str,
        runner_cls: str,
        pid: int,
        hostname: str,
        thread_id: int,
        parent_runner_id: str | None = None,
        parent_runner_cls: str | None = None,
    ) -> None: ...
    def get_runner_context(self, runner_id: str) -> str | None: ...
    def get_all_runner_contexts(self) -> list[tuple[str, str]]: ...
    def remove_runner_context(self, runner_id: str) -> None: ...
    def heartbeat_runner(self, runner_id: str) -> None: ...
    def get_stale_runners(self, timeout_seconds: int) -> list[tuple[str, str]]: ...

class RustMongoStateBackend:
    def __init__(self, pool: RustMongoPool) -> None: ...
    def upsert_invocation(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        parent_invocation_id: str | None = None,
        workflow_json: str | None = None,
    ) -> None: ...
    def store_result(self, invocation_id: str, result: str) -> None: ...
    def get_result(self, invocation_id: str) -> str | None: ...
    def store_error(self, invocation_id: str, error_type: str, message: str, traceback: str | None = None) -> None: ...
    def get_error(self, invocation_id: str) -> str | None: ...
    def get_error_json(self, invocation_id: str) -> str | None: ...
    def purge(self) -> None: ...
    def add_history(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
        runner_context_id: str | None = None,
        message: str | None = None,
        sr_timestamp_us: int | None = None,
        history_timestamp_us: int | None = None,
    ) -> None: ...
    def get_history(self, invocation_id: str) -> str: ...
    def get_invocation(self, invocation_id: str) -> str: ...
    def get_call(self, call_id: str) -> str: ...
    def get_child_invocations(self, parent_invocation_id: str) -> list[str]: ...
    def store_workflow_run(self, workflow_json: str) -> None: ...
    def get_all_workflow_types(self) -> list[str]: ...
    def get_workflow_runs(self, task_module: str, task_name: str) -> list[str]: ...
    def set_workflow_data(self, workflow_invocation_id: str, key: str, value: str) -> None: ...
    def get_workflow_data(self, workflow_invocation_id: str, key: str) -> str | None: ...
    def get_workflow_invocations(self, workflow_id: str) -> list[str]: ...
    def store_app_info(self, app_id: str, info_json: str) -> None: ...
    def get_app_info(self, app_id: str) -> str | None: ...
    def get_all_app_infos(self) -> list[tuple[str, str]]: ...
    def store_workflow_sub_invocation(self, workflow_id: str, sub_invocation_id: str) -> None: ...
    def get_workflow_sub_invocations(self, workflow_id: str) -> list[str]: ...
    def get_all_workflow_runs(self) -> list[str]: ...
    def store_runner_context(
        self,
        runner_id: str,
        runner_cls: str,
        pid: int,
        hostname: str,
        thread_id: int,
        parent_runner_id: str | None = None,
        parent_runner_cls: str | None = None,
    ) -> None: ...
    def get_runner_context(self, runner_id: str) -> str | None: ...
    def get_all_runner_contexts(self) -> list[tuple[str, str]]: ...
    def remove_runner_context(self, runner_id: str) -> None: ...
    def heartbeat_runner(self, runner_id: str) -> None: ...
    def get_stale_runners(self, timeout_seconds: int) -> list[tuple[str, str]]: ...

class RustMongo3StateBackend:
    def __init__(self, pool: RustMongo3Pool) -> None: ...
    def upsert_invocation(
        self,
        invocation_id: str,
        task_module: str,
        task_name: str,
        serialized_arguments: dict[str, str],
        parent_invocation_id: str | None = None,
        workflow_json: str | None = None,
    ) -> None: ...
    def store_result(self, invocation_id: str, result: str) -> None: ...
    def get_result(self, invocation_id: str) -> str | None: ...
    def store_error(self, invocation_id: str, error_type: str, message: str, traceback: str | None = None) -> None: ...
    def get_error(self, invocation_id: str) -> str | None: ...
    def get_error_json(self, invocation_id: str) -> str | None: ...
    def purge(self) -> None: ...
    def add_history(
        self,
        invocation_id: str,
        status: str,
        runner_id: str | None = None,
        runner_context_id: str | None = None,
        message: str | None = None,
        sr_timestamp_us: int | None = None,
        history_timestamp_us: int | None = None,
    ) -> None: ...
    def get_history(self, invocation_id: str) -> str: ...
    def get_invocation(self, invocation_id: str) -> str: ...
    def get_call(self, call_id: str) -> str: ...
    def get_child_invocations(self, parent_invocation_id: str) -> list[str]: ...
    def store_workflow_run(self, workflow_json: str) -> None: ...
    def get_all_workflow_types(self) -> list[str]: ...
    def get_workflow_runs(self, task_module: str, task_name: str) -> list[str]: ...
    def set_workflow_data(self, workflow_invocation_id: str, key: str, value: str) -> None: ...
    def get_workflow_data(self, workflow_invocation_id: str, key: str) -> str | None: ...
    def get_workflow_invocations(self, workflow_id: str) -> list[str]: ...
    def store_app_info(self, app_id: str, info_json: str) -> None: ...
    def get_app_info(self, app_id: str) -> str | None: ...
    def get_all_app_infos(self) -> list[tuple[str, str]]: ...
    def store_workflow_sub_invocation(self, workflow_id: str, sub_invocation_id: str) -> None: ...
    def get_workflow_sub_invocations(self, workflow_id: str) -> list[str]: ...
    def get_all_workflow_runs(self) -> list[str]: ...
    def store_runner_context(
        self,
        runner_id: str,
        runner_cls: str,
        pid: int,
        hostname: str,
        thread_id: int,
        parent_runner_id: str | None = None,
        parent_runner_cls: str | None = None,
    ) -> None: ...
    def get_runner_context(self, runner_id: str) -> str | None: ...
    def get_all_runner_contexts(self) -> list[tuple[str, str]]: ...
    def remove_runner_context(self, runner_id: str) -> None: ...
    def heartbeat_runner(self, runner_id: str) -> None: ...
    def get_stale_runners(self, timeout_seconds: int) -> list[tuple[str, str]]: ...

# ============================================================================
# Broker — all backends share the same methods
# ============================================================================

class RustMemBroker:
    def __init__(self) -> None: ...
    def route_invocation(self, invocation_id: str) -> None: ...
    def route_invocations(self, invocation_ids: list[str]) -> None: ...
    def retrieve_invocation(self) -> str | None: ...
    def count_invocations(self) -> int: ...
    def purge(self) -> None: ...
    def route_invocation_for_task(self, invocation_id: str, task_module: str, task_name: str) -> None: ...
    def retrieve_invocation_for_task(self, task_module: str, task_name: str) -> str | None: ...
    def retrieve_invocation_for_language(self, language: str) -> str | None: ...
    def count_invocations_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge_task(self, task_module: str, task_name: str) -> None: ...

class RustSqliteBroker:
    def __init__(self, db: RustSqliteDatabase) -> None: ...
    def route_invocation(self, invocation_id: str) -> None: ...
    def route_invocations(self, invocation_ids: list[str]) -> None: ...
    def retrieve_invocation(self) -> str | None: ...
    def count_invocations(self) -> int: ...
    def purge(self) -> None: ...
    def route_invocation_for_task(self, invocation_id: str, task_module: str, task_name: str) -> None: ...
    def retrieve_invocation_for_task(self, task_module: str, task_name: str) -> str | None: ...
    def retrieve_invocation_for_language(self, language: str) -> str | None: ...
    def count_invocations_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge_task(self, task_module: str, task_name: str) -> None: ...

class RustPostgresBroker:
    def __init__(self, db: RustPostgresDatabase) -> None: ...
    def route_invocation(self, invocation_id: str) -> None: ...
    def route_invocations(self, invocation_ids: list[str]) -> None: ...
    def retrieve_invocation(self) -> str | None: ...
    def count_invocations(self) -> int: ...
    def purge(self) -> None: ...
    def route_invocation_for_task(self, invocation_id: str, task_module: str, task_name: str) -> None: ...
    def retrieve_invocation_for_task(self, task_module: str, task_name: str) -> str | None: ...
    def retrieve_invocation_for_language(self, language: str) -> str | None: ...
    def count_invocations_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge_task(self, task_module: str, task_name: str) -> None: ...

class RustRedisBroker:
    def __init__(self, pool: RustRedisPool) -> None: ...
    def route_invocation(self, invocation_id: str) -> None: ...
    def route_invocations(self, invocation_ids: list[str]) -> None: ...
    def retrieve_invocation(self) -> str | None: ...
    def count_invocations(self) -> int: ...
    def purge(self) -> None: ...
    def route_invocation_for_task(self, invocation_id: str, task_module: str, task_name: str) -> None: ...
    def retrieve_invocation_for_task(self, task_module: str, task_name: str) -> str | None: ...
    def retrieve_invocation_for_language(self, language: str) -> str | None: ...
    def count_invocations_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge_task(self, task_module: str, task_name: str) -> None: ...

class RustMongoBroker:
    def __init__(self, pool: RustMongoPool) -> None: ...
    def route_invocation(self, invocation_id: str) -> None: ...
    def route_invocations(self, invocation_ids: list[str]) -> None: ...
    def retrieve_invocation(self) -> str | None: ...
    def count_invocations(self) -> int: ...
    def purge(self) -> None: ...
    def route_invocation_for_task(self, invocation_id: str, task_module: str, task_name: str) -> None: ...
    def retrieve_invocation_for_task(self, task_module: str, task_name: str) -> str | None: ...
    def retrieve_invocation_for_language(self, language: str) -> str | None: ...
    def count_invocations_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge_task(self, task_module: str, task_name: str) -> None: ...

class RustMongo3Broker:
    def __init__(self, pool: RustMongo3Pool) -> None: ...
    def route_invocation(self, invocation_id: str) -> None: ...
    def route_invocations(self, invocation_ids: list[str]) -> None: ...
    def retrieve_invocation(self) -> str | None: ...
    def count_invocations(self) -> int: ...
    def purge(self) -> None: ...
    def route_invocation_for_task(self, invocation_id: str, task_module: str, task_name: str) -> None: ...
    def retrieve_invocation_for_task(self, task_module: str, task_name: str) -> str | None: ...
    def retrieve_invocation_for_language(self, language: str) -> str | None: ...
    def count_invocations_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge_task(self, task_module: str, task_name: str) -> None: ...

class RustRabbitmqBroker:
    def __init__(self, uri: str, prefix: str) -> None: ...
    def route_invocation(self, invocation_id: str) -> None: ...
    def route_invocations(self, invocation_ids: list[str]) -> None: ...
    def retrieve_invocation(self) -> str | None: ...
    def count_invocations(self) -> int: ...
    def purge(self) -> None: ...
    def route_invocation_for_task(self, invocation_id: str, task_module: str, task_name: str) -> None: ...
    def retrieve_invocation_for_task(self, task_module: str, task_name: str) -> str | None: ...
    def retrieve_invocation_for_language(self, language: str) -> str | None: ...
    def count_invocations_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge_task(self, task_module: str, task_name: str) -> None: ...

# ============================================================================
# Trigger Store — all backends share the same methods
# ============================================================================

class RustMemTriggerStore:
    def __init__(self) -> None: ...
    def register_condition(self, condition_json: str) -> str: ...
    def get_condition(self, condition_id: str) -> str | None: ...
    def register_trigger(self, trigger_json: str) -> None: ...
    def get_trigger(self, trigger_id: str) -> str | None: ...
    def get_triggers_for_condition(self, condition_id: str) -> list[str]: ...
    def get_conditions_for_task(self, task_module: str, task_name: str) -> list[tuple[str, str]]: ...
    def get_all_conditions(self) -> list[tuple[str, str]]: ...
    def remove_triggers_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge(self) -> None: ...
    def record_valid_condition(self, valid_condition_json: str) -> None: ...
    def get_valid_conditions(self) -> list[str]: ...
    def clear_valid_conditions(self, valid_condition_ids: list[str]) -> None: ...
    def get_last_cron_execution(self, condition_id: str) -> float | None: ...
    def store_cron_execution(
        self, condition_id: str, execution_timestamp: float, expected_last_timestamp: float | None = None
    ) -> bool: ...
    def claim_trigger_run(self, trigger_run_id: str) -> bool: ...
    def report_status_change(self, invocation_id: str, task_module: str, task_name: str, status: str) -> list[str]: ...
    def report_result(self, invocation_id: str, task_module: str, task_name: str, result: str) -> list[str]: ...
    def report_failure(
        self, invocation_id: str, task_module: str, task_name: str, error_type: str, error_message: str
    ) -> list[str]: ...
    def emit_event(self, event_code: str, payload_json: str) -> str: ...
    def evaluate_cron_conditions(self) -> list[str]: ...
    def evaluate_triggers(self) -> list[tuple[str, str]]: ...
    def register_status_condition(
        self, task_module: str, task_name: str, statuses: list[str], argument_filter_json: str | None = None
    ) -> str: ...
    def register_cron_condition(self, cron_expression: str, min_interval_seconds: int = 0) -> str: ...
    def register_event_condition(self, event_code: str, payload_filter_json: str | None = None) -> str: ...

class RustSqliteTriggerStore:
    def __init__(self, db: RustSqliteDatabase) -> None: ...
    def register_condition(self, condition_json: str) -> str: ...
    def get_condition(self, condition_id: str) -> str | None: ...
    def register_trigger(self, trigger_json: str) -> None: ...
    def get_trigger(self, trigger_id: str) -> str | None: ...
    def get_triggers_for_condition(self, condition_id: str) -> list[str]: ...
    def get_conditions_for_task(self, task_module: str, task_name: str) -> list[tuple[str, str]]: ...
    def get_all_conditions(self) -> list[tuple[str, str]]: ...
    def remove_triggers_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge(self) -> None: ...
    def record_valid_condition(self, valid_condition_json: str) -> None: ...
    def get_valid_conditions(self) -> list[str]: ...
    def clear_valid_conditions(self, valid_condition_ids: list[str]) -> None: ...
    def get_last_cron_execution(self, condition_id: str) -> float | None: ...
    def store_cron_execution(
        self, condition_id: str, execution_timestamp: float, expected_last_timestamp: float | None = None
    ) -> bool: ...
    def claim_trigger_run(self, trigger_run_id: str) -> bool: ...
    def report_status_change(self, invocation_id: str, task_module: str, task_name: str, status: str) -> list[str]: ...
    def report_result(self, invocation_id: str, task_module: str, task_name: str, result: str) -> list[str]: ...
    def report_failure(
        self, invocation_id: str, task_module: str, task_name: str, error_type: str, error_message: str
    ) -> list[str]: ...
    def emit_event(self, event_code: str, payload_json: str) -> str: ...
    def evaluate_cron_conditions(self) -> list[str]: ...
    def evaluate_triggers(self) -> list[tuple[str, str]]: ...
    def register_status_condition(
        self, task_module: str, task_name: str, statuses: list[str], argument_filter_json: str | None = None
    ) -> str: ...
    def register_cron_condition(self, cron_expression: str, min_interval_seconds: int = 0) -> str: ...
    def register_event_condition(self, event_code: str, payload_filter_json: str | None = None) -> str: ...

class RustPostgresTriggerStore:
    def __init__(self, db: RustPostgresDatabase) -> None: ...
    def register_condition(self, condition_json: str) -> str: ...
    def get_condition(self, condition_id: str) -> str | None: ...
    def register_trigger(self, trigger_json: str) -> None: ...
    def get_trigger(self, trigger_id: str) -> str | None: ...
    def get_triggers_for_condition(self, condition_id: str) -> list[str]: ...
    def get_conditions_for_task(self, task_module: str, task_name: str) -> list[tuple[str, str]]: ...
    def get_all_conditions(self) -> list[tuple[str, str]]: ...
    def remove_triggers_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge(self) -> None: ...
    def record_valid_condition(self, valid_condition_json: str) -> None: ...
    def get_valid_conditions(self) -> list[str]: ...
    def clear_valid_conditions(self, valid_condition_ids: list[str]) -> None: ...
    def get_last_cron_execution(self, condition_id: str) -> float | None: ...
    def store_cron_execution(
        self, condition_id: str, execution_timestamp: float, expected_last_timestamp: float | None = None
    ) -> bool: ...
    def claim_trigger_run(self, trigger_run_id: str) -> bool: ...
    def report_status_change(self, invocation_id: str, task_module: str, task_name: str, status: str) -> list[str]: ...
    def report_result(self, invocation_id: str, task_module: str, task_name: str, result: str) -> list[str]: ...
    def report_failure(
        self, invocation_id: str, task_module: str, task_name: str, error_type: str, error_message: str
    ) -> list[str]: ...
    def emit_event(self, event_code: str, payload_json: str) -> str: ...
    def evaluate_cron_conditions(self) -> list[str]: ...
    def evaluate_triggers(self) -> list[tuple[str, str]]: ...
    def register_status_condition(
        self, task_module: str, task_name: str, statuses: list[str], argument_filter_json: str | None = None
    ) -> str: ...
    def register_cron_condition(self, cron_expression: str, min_interval_seconds: int = 0) -> str: ...
    def register_event_condition(self, event_code: str, payload_filter_json: str | None = None) -> str: ...

class RustRedisTriggerStore:
    def __init__(self, pool: RustRedisPool) -> None: ...
    def register_condition(self, condition_json: str) -> str: ...
    def get_condition(self, condition_id: str) -> str | None: ...
    def register_trigger(self, trigger_json: str) -> None: ...
    def get_trigger(self, trigger_id: str) -> str | None: ...
    def get_triggers_for_condition(self, condition_id: str) -> list[str]: ...
    def get_conditions_for_task(self, task_module: str, task_name: str) -> list[tuple[str, str]]: ...
    def get_all_conditions(self) -> list[tuple[str, str]]: ...
    def remove_triggers_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge(self) -> None: ...
    def record_valid_condition(self, valid_condition_json: str) -> None: ...
    def get_valid_conditions(self) -> list[str]: ...
    def clear_valid_conditions(self, valid_condition_ids: list[str]) -> None: ...
    def get_last_cron_execution(self, condition_id: str) -> float | None: ...
    def store_cron_execution(
        self, condition_id: str, execution_timestamp: float, expected_last_timestamp: float | None = None
    ) -> bool: ...
    def claim_trigger_run(self, trigger_run_id: str) -> bool: ...
    def report_status_change(self, invocation_id: str, task_module: str, task_name: str, status: str) -> list[str]: ...
    def report_result(self, invocation_id: str, task_module: str, task_name: str, result: str) -> list[str]: ...
    def report_failure(
        self, invocation_id: str, task_module: str, task_name: str, error_type: str, error_message: str
    ) -> list[str]: ...
    def emit_event(self, event_code: str, payload_json: str) -> str: ...
    def evaluate_cron_conditions(self) -> list[str]: ...
    def evaluate_triggers(self) -> list[tuple[str, str]]: ...
    def register_status_condition(
        self, task_module: str, task_name: str, statuses: list[str], argument_filter_json: str | None = None
    ) -> str: ...
    def register_cron_condition(self, cron_expression: str, min_interval_seconds: int = 0) -> str: ...
    def register_event_condition(self, event_code: str, payload_filter_json: str | None = None) -> str: ...

class RustMongoTriggerStore:
    def __init__(self, pool: RustMongoPool) -> None: ...
    def register_condition(self, condition_json: str) -> str: ...
    def get_condition(self, condition_id: str) -> str | None: ...
    def register_trigger(self, trigger_json: str) -> None: ...
    def get_trigger(self, trigger_id: str) -> str | None: ...
    def get_triggers_for_condition(self, condition_id: str) -> list[str]: ...
    def get_conditions_for_task(self, task_module: str, task_name: str) -> list[tuple[str, str]]: ...
    def get_all_conditions(self) -> list[tuple[str, str]]: ...
    def remove_triggers_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge(self) -> None: ...
    def record_valid_condition(self, valid_condition_json: str) -> None: ...
    def get_valid_conditions(self) -> list[str]: ...
    def clear_valid_conditions(self, valid_condition_ids: list[str]) -> None: ...
    def get_last_cron_execution(self, condition_id: str) -> float | None: ...
    def store_cron_execution(
        self, condition_id: str, execution_timestamp: float, expected_last_timestamp: float | None = None
    ) -> bool: ...
    def claim_trigger_run(self, trigger_run_id: str) -> bool: ...
    def report_status_change(self, invocation_id: str, task_module: str, task_name: str, status: str) -> list[str]: ...
    def report_result(self, invocation_id: str, task_module: str, task_name: str, result: str) -> list[str]: ...
    def report_failure(
        self, invocation_id: str, task_module: str, task_name: str, error_type: str, error_message: str
    ) -> list[str]: ...
    def emit_event(self, event_code: str, payload_json: str) -> str: ...
    def evaluate_cron_conditions(self) -> list[str]: ...
    def evaluate_triggers(self) -> list[tuple[str, str]]: ...
    def register_status_condition(
        self, task_module: str, task_name: str, statuses: list[str], argument_filter_json: str | None = None
    ) -> str: ...
    def register_cron_condition(self, cron_expression: str, min_interval_seconds: int = 0) -> str: ...
    def register_event_condition(self, event_code: str, payload_filter_json: str | None = None) -> str: ...

class RustMongo3TriggerStore:
    def __init__(self, pool: RustMongo3Pool) -> None: ...
    def register_condition(self, condition_json: str) -> str: ...
    def get_condition(self, condition_id: str) -> str | None: ...
    def register_trigger(self, trigger_json: str) -> None: ...
    def get_trigger(self, trigger_id: str) -> str | None: ...
    def get_triggers_for_condition(self, condition_id: str) -> list[str]: ...
    def get_conditions_for_task(self, task_module: str, task_name: str) -> list[tuple[str, str]]: ...
    def get_all_conditions(self) -> list[tuple[str, str]]: ...
    def remove_triggers_for_task(self, task_module: str, task_name: str) -> int: ...
    def purge(self) -> None: ...
    def record_valid_condition(self, valid_condition_json: str) -> None: ...
    def get_valid_conditions(self) -> list[str]: ...
    def clear_valid_conditions(self, valid_condition_ids: list[str]) -> None: ...
    def get_last_cron_execution(self, condition_id: str) -> float | None: ...
    def store_cron_execution(
        self, condition_id: str, execution_timestamp: float, expected_last_timestamp: float | None = None
    ) -> bool: ...
    def claim_trigger_run(self, trigger_run_id: str) -> bool: ...
    def report_status_change(self, invocation_id: str, task_module: str, task_name: str, status: str) -> list[str]: ...
    def report_result(self, invocation_id: str, task_module: str, task_name: str, result: str) -> list[str]: ...
    def report_failure(
        self, invocation_id: str, task_module: str, task_name: str, error_type: str, error_message: str
    ) -> list[str]: ...
    def emit_event(self, event_code: str, payload_json: str) -> str: ...
    def evaluate_cron_conditions(self) -> list[str]: ...
    def evaluate_triggers(self) -> list[tuple[str, str]]: ...
    def register_status_condition(
        self, task_module: str, task_name: str, statuses: list[str], argument_filter_json: str | None = None
    ) -> str: ...
    def register_cron_condition(self, cron_expression: str, min_interval_seconds: int = 0) -> str: ...
    def register_event_condition(self, event_code: str, payload_filter_json: str | None = None) -> str: ...

# ============================================================================
# Client Data Store — all backends share the same methods
# ============================================================================

class RustMemClientDataStore:
    def __init__(
        self, min_size_to_cache: int = 1024, max_size_to_cache: int = 0, local_cache_size: int = 128
    ) -> None: ...
    def store_if_large(self, serialized: str) -> str: ...
    def resolve(self, data: str) -> str: ...
    def store(self, key: str, value: str) -> None: ...
    def retrieve(self, key: str) -> str: ...
    def purge(self) -> None: ...
    def backend_name(self) -> str: ...

class RustSqliteClientDataStore:
    def __init__(
        self,
        db: RustSqliteDatabase,
        min_size_to_cache: int = 1024,
        max_size_to_cache: int = 0,
        local_cache_size: int = 128,
    ) -> None: ...
    def store_if_large(self, serialized: str) -> str: ...
    def resolve(self, data: str) -> str: ...
    def store(self, key: str, value: str) -> None: ...
    def retrieve(self, key: str) -> str: ...
    def purge(self) -> None: ...
    def backend_name(self) -> str: ...

class RustPostgresClientDataStore:
    def __init__(
        self,
        db: RustPostgresDatabase,
        min_size_to_cache: int = 1024,
        max_size_to_cache: int = 0,
        local_cache_size: int = 128,
    ) -> None: ...
    def store_if_large(self, serialized: str) -> str: ...
    def resolve(self, data: str) -> str: ...
    def store(self, key: str, value: str) -> None: ...
    def retrieve(self, key: str) -> str: ...
    def purge(self) -> None: ...
    def backend_name(self) -> str: ...

class RustRedisClientDataStore:
    def __init__(
        self,
        pool: RustRedisPool,
        min_size_to_cache: int = 1024,
        max_size_to_cache: int = 0,
        local_cache_size: int = 128,
    ) -> None: ...
    def store_if_large(self, serialized: str) -> str: ...
    def resolve(self, data: str) -> str: ...
    def store(self, key: str, value: str) -> None: ...
    def retrieve(self, key: str) -> str: ...
    def purge(self) -> None: ...
    def backend_name(self) -> str: ...

class RustMongoClientDataStore:
    def __init__(
        self,
        pool: RustMongoPool,
        min_size_to_cache: int = 1024,
        max_size_to_cache: int = 0,
        local_cache_size: int = 128,
    ) -> None: ...
    def store_if_large(self, serialized: str) -> str: ...
    def resolve(self, data: str) -> str: ...
    def store(self, key: str, value: str) -> None: ...
    def retrieve(self, key: str) -> str: ...
    def purge(self) -> None: ...
    def backend_name(self) -> str: ...

class RustMongo3ClientDataStore:
    def __init__(
        self,
        pool: RustMongo3Pool,
        min_size_to_cache: int = 1024,
        max_size_to_cache: int = 0,
        local_cache_size: int = 128,
    ) -> None: ...
    def store_if_large(self, serialized: str) -> str: ...
    def resolve(self, data: str) -> str: ...
    def store(self, key: str, value: str) -> None: ...
    def retrieve(self, key: str) -> str: ...
    def purge(self) -> None: ...
    def backend_name(self) -> str: ...

# ============================================================================
# Exception classes
# ============================================================================

class RustvelloError(Exception): ...
class BrokerError(RustvelloError): ...
class ConfigurationError(RustvelloError): ...
class InternalError(RustvelloError): ...
class InvocationError(RustvelloError): ...

class InvocationNotFoundError(InvocationError):
    invocation_id: str

class InvocationStatusError(InvocationError): ...

class StatusOwnershipError(InvocationStatusError):
    invocation_id: str
    from_status: str
    to_status: str
    current_owner: str
    attempted_owner: str
    reason: str

class StatusRaceConditionError(InvocationStatusError):
    invocation_id: str
    previous_status: str
    expected_status: str
    actual_status: str

class StatusTransitionError(InvocationStatusError):
    invocation_id: str
    from_status: str
    to_status: str
    allowed_statuses: list[str]

class RetryError(RustvelloError): ...
class ConcurrencyRetryError(RetryError): ...
class RunnerError(RustvelloError): ...
class SerializationError(RustvelloError): ...
class StateBackendError(RustvelloError): ...
class TaskError(RustvelloError): ...
class CycleDetectedError(TaskError): ...
class RunnerNotExecutableError(TaskError): ...
class TaskClassNotFoundError(TaskError): ...
class TaskNotFoundError(TaskError): ...
class TaskNotRegisteredError(TaskError): ...
